# -*- coding: utf-8 -*-
"""fintech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uql-hxoCxIfxvc7x3VLN0RR2OeOXO7z
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import joblib

# Generate random data
n_samples = 1000
time_on_books = np.random.randint(1, 61, n_samples)  # months on books
total_paid_last_12_months = np.random.uniform(0, 50000, n_samples)
total_debt_in_arrears = np.random.uniform(0, 100000, n_samples)

# Create some underlying probability for paying debt
# Higher payments and lower arrears increase likelihood of paying
prob_pay = 1 / (1 + np.exp(-(
    0.05 * time_on_books +
    0.0001 * total_paid_last_12_months -
    0.00005 * total_debt_in_arrears -
    2
)))

# Binary target variable: 1 = pay, 0 = not pay
pay = np.random.binomial(1, prob_pay)

# Create DataFrame
df = pd.DataFrame({
    'time_on_books': time_on_books,
    'total_paid_last_12_months': total_paid_last_12_months,
    'total_debt_in_arrears': total_debt_in_arrears,
    'pay': pay
})

# Save to Excel without index
df.to_excel('fintech.xlsx', index=False)

# Split into features and target
X = df[['time_on_books', 'total_paid_last_12_months', 'total_debt_in_arrears']]
y = df['pay']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create and train logistic regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predictions
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Validation - classification reports
print("Classification Report - Train Data:")
print(classification_report(y_train, y_train_pred))

print("\nClassification Report - Test Data:")
print(classification_report(y_test, y_test_pred))

# Save model to joblib file
joblib.dump(model, 'fintech.joblib')

print("\nModel and dataset saved successfully.")